language: android
jdk: oraclejdk8
dist: trusty
env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-24
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

script:
  ./gradlew build test ./gradlew assembleRelease

